### PR TITLE
Maps

### PR DESCRIPTION
**Pull request by floamahe**
added a map on index and a map on show, without markers

### CODE REVIEW

**Comment by floamahe** [comment]
after pull run on your machines
`bundle instal`
`rails db:migrate`
`yarn add mapbox-gl`

in your .env file, add 
MAPBOX_API_KEY=**_your key_**

**Comment by floamahe** [comment]
additional step for production :

To make it work on Heroku, push your MapBox API Key:

`heroku config:set MAPBOX_API_KEY=pk.eyJ1IjoicGR1b****************yZvNpTR_kk1kKqQ`

**Comment by Gueram** [comment]
Is it secure to push my API key ?

**Comment by floamahe** [comment]
> 
> 
> Is it secure to push my API key ?

I think we shoud ask a TA

**Comment by Gueram** [comment]
TA said it is send in SHH so it is

**Pull request merged**
